version: "3.7"

services:
    web:
        build:
            context: .
        entrypoint: yarn dev
        volumes:
            - .:/app/
            - /app/node_modules
        ports:
            - 3000:3000
